default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: standby_doc_development

test:
  <<: *default
  database: standby_doc_test

production:
  <<: *default
  database: standby_doc_production
